config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'pages/home'
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.roles.include? "admin"
      can :manage, :all
    end

    if user.roles.include? "redactor"
      can :read, ActiveAdmin::Page, name: "Dashboard"
      can :manage, [Region, School, District, City, Educational::Level,
                    Educational::Program, Educational::ProgramType, Educational::UgsCode,
                    Educational::Unit
      ]
    end

    if user.roles.include? "user"
      can :read, ActiveAdmin::Page, name: "Dashboard"
      can :read, [Region, School, District, City]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :region, optional: true
  has_one :district, through: :region
  has_many :schools

  class << self
    def ransackable_scopes(auth_object = nil)
      %i( name_select_in )
    end

    def ransackable_scopes_skip_sanitize_args
      %i( name_select_in )
    end

    def name_select_in(*params)
      where(id: params)
    end
  end

  def delete_schools
    schools.delete_all
  end
end

app/models/district.rb
class District < ApplicationRecord
  has_many :regions
  has_many :cities, through: :regions
  has_many :schools, through: :cities

end

app/models/educational.rb
module Educational
  def self.table_name_prefix
    'educational_'
  end
end

app/models/educational/level.rb
class Educational::Level < ApplicationRecord
end

app/models/educational/program.rb
class Educational::Program < ApplicationRecord
  belongs_to :program_type, class_name: 'Educational::ProgramType', optional: true
  belongs_to :ugs_code, class_name: 'Educational::UgsCode', optional: true
  belongs_to :level, class_name: 'Educational::Level', optional: true
  has_and_belongs_to_many :units, class_name: 'Educational::Unit'

  def title
    name || level&.name
  end

end

app/models/educational/program_type.rb
class Educational::ProgramType < ApplicationRecord
  has_many :programs, class_name: 'Educational::Program'
end

app/models/educational/ugs_code.rb
class Educational::UgsCode < ApplicationRecord
  has_many :programs, :class_name => 'Educational::Program'
end

app/models/educational/unit.rb
class Educational::Unit < ApplicationRecord
  belongs_to :region, class_name: 'Region'
  has_and_belongs_to_many :programs, class_name: 'Educational::Program'
  has_many :levels, :class_name => 'Educational::Level', through: :programs
  has_one :district, class_name: 'District', through: :region

end

app/models/region.rb
class Region < ApplicationRecord
  belongs_to :district, optional: true
  has_many :cities
  has_many :schools, through: :cities

end

app/models/school.rb
class School < ApplicationRecord
  belongs_to :city, counter_cache: true
  has_one :region, through: :city, source: :region
  has_one :district, through: :region, source: :district

  FIND_PATTERN = {
      email: /([a-z\-\–_\d\.]*@[a-z\d]*\.[a-z]*)+/i,
      phone: /([\d\+\-\(\)]+)+/,
      site: /[[:word:]*:\/\/]*[[:word:]-]*\.[[:word:]-]*[\.[:word:]-]*/i,
  }

end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :user_roles

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  accepts_nested_attributes_for :user_roles

  validates :username, presence: true, uniqueness: { case_sensitive: false }
    validate :validate_username
    attr_writer :login

  def roles
    user_roles.pluck(:role)
  end

  def login
    @login || username || email
  end

  def validate_username
    errors.add(:username, :invalid) if User.where(username: username).exists?
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(['lower(username) = :value OR lower(email) = :value', { value: login.downcase }]).first
    elsif conditions.key?(:username) || conditions.key?(:email)
      where(conditions.to_h).first
    end
  end

end

app/models/user_role.rb
class UserRole < ApplicationRecord
  has_and_belongs_to_many :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navbar.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  = link_to Rails.application.class.parent_name, root_path, class:"navbar-brand"
  button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"]
    span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      li.nav-item.active
        = link_to "Главная", root_path, class:"nav-link"
      - if current_user
        li.nav-item
          =link_to 'Админка', admin_root_path, class: 'nav-link'

    ul.navbar-nav.ml-auto
      - if current_user
        li.nav-item.dropdown
          a#navbarDropdown.nav-link.dropdown-toggle[href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"]
            = current_user.username
          .dropdown-menu.dropdown-menu-right[aria-labelledby="navbarDropdown"]
            = link_to "Выйти", destroy_user_session_path, method: :delete, class:"dropdown-item"
      - else
        li.nav-item
          = link_to "Войти", new_user_session_path, class:"nav-link"

app/views/layouts/application.slim
doctype html
html
  head
    title Serving Static Files
    = stylesheet_pack_tag "application", media: "all"
    = javascript_pack_tag "application"
    = csrf_meta_tags
  body
    = render 'layouts/navbar'
    = yield

app/views/pages/home.html.slim
h1 Здравствуйте